# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: enviroment
  displayName: 'Seleccione Ambiente'  
  type: string
  default: prod
  values:
  - prod

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
  # Replace '10.14' with the latest Node.js LTS version
    versionSpec: '14.17.6'
  displayName: 'Install Node.js'
  
- script: npm install
  displayName: 'Install Dependencies'

- script: npm install --save-dev testcafe -g
  displayName: 'Install TestCafe'
  
- script: npm install --save testcafe-reporter-cucumber-json
  displayName: 'Install Reporter json '  

- script: npm install --save downloads-folder
  displayName: 'Install Downloads Folder'  

- script: ENV=${{ parameters.enviroment }}  testcafe chrome:headless ./test/OCL -f "Suite Pruebas iConstruye Crear copia de Usuario" --skip-js-errors --reporter cucumber-json,xunit:report01.xml --reporter-json-folder=reports/jsonReport
  condition: succeededOrFailed()
  displayName: 'Suite Pruebas iConstruye Crear copia de Usuario'

- script: ENV=${{ parameters.enviroment }}  testcafe chrome:headless ./test/OCL -f "Suite Pruebas iConstruye Reemplazar Usuario" --skip-js-errors --reporter cucumber-json,xunit:report02.xml --reporter-json-folder=reports/jsonReport
  condition: succeededOrFailed()
  displayName: 'Suite Pruebas iConstruye Reemplazar Usuario'

- script: npm run report
  condition: succeededOrFailed()
  displayName: 'Multiple Cucumber HTML Report Generate'
    
- task: PublishTestResults@2
  condition: succeededOrFailed() 
  inputs:
    testResultsFiles: 'report*.xml'
    testResultsFormat: 'JUnit'
    
- task: PublishCucumberReport@1
  condition: succeededOrFailed()
  displayName: 'Publish Cucumber Report'
  inputs:
    jsonDir: ./reports/jsonReport
    outputPath: ./reports
    theme: hierarchy
    name: 'Reporte de Pruebas Automaticas en OneClick'
    title: 'Reporte de Pruebas Automaticas en OneClick'

- task: PublishPipelineArtifact@1
  condition: succeededOrFailed()
  displayName: 'Publish HTML Report'
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/reports/htmlReport'
    artifactType: 'pipeline'
    artifactName: 'htmlReport'

schedules:
  - cron: "0 8 * * *"
    displayName: Daily Test Execution
    branches:
      include:
      - master
    always: true
